routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\JurnalController;
use App\Http\Controllers\PresensiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect()->to('/jurnal');
});

Route::resource('jurnal', JurnalController::class);
Route::resource('presensi', PresensiController::class);
Route::get('hadir/{jurnalID}', [PresensiController::class, 'hadir']);
Route::get('rekap',[PresensiController::class,'rekap']);

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/jurnal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class jurnal extends Model
{
    use HasFactory;
    protected $table = 'jurnals';
    protected $primaryKey = "id";
    protected $guarded = ['id'];

    public function presensi(){
        return $this->hasMany(presensi::class, 'id', 'jurnals_id');
    }
}

app/Models/presensi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class presensi extends Model
{
    use HasFactory;
    protected $table='presensis';
    protected $guarded=['id'];

    public function jurnal(){
        return $this->belongsTo(jurnal::class, 'jurnals_id', 'id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/JurnalController.php
<?php

namespace App\Http\Controllers;

use App\Models\jurnal;
use Illuminate\Http\Request;

class JurnalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $jurnals = jurnal::orderBy('id','desc')->paginate(20);
        return view('jurnal.index')->with(['jurnals' => $jurnals]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = null;
        $jurnalID = $this->jurnalID();
        return view('jurnal.form')->with(['jurnal'=>$data,'jurnalID'=>$jurnalID]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Jurnal::create($request->all());
        return redirect()->route('jurnal.index')->with('success','Jurnal Tersimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\jurnal  $jurnal
     * @return \Illuminate\Http\Response
     */
    public function show(jurnal $jurnal)
    {
        return view('jurnal.detail')->with('jurnal', $jurnal);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\jurnal  $jurnal
     * @return \Illuminate\Http\Response
     */
    public function edit(jurnal $jurnal)
    {
        $data = $jurnal;
        return view('jurnal.form')->with(['jurnal'=>$data,'jurnalID'=>$jurnal->jurnalID]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\jurnal  $jurnal
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, jurnal $jurnal)
    {
        $jurnal->id = $request->id;
        $jurnal->jurnalID = $request->jurnalID;
        $jurnal->tanggal = $request->tanggal;
        $jurnal->kelas = $request->kelas;
        $jurnal->pelajaran = $request->pelajaran;
        $jurnal->topik = $request->topik;
        $jurnal->tutor = $request->tutor;
        $jurnal->dokumen = $request->dokumen;
        $jurnal->save();
        return redirect()->route('jurnal.index')->with('success','Jurnal diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\jurnal  $jurnal
     * @return \Illuminate\Http\Response
     */
    public function destroy(jurnal $jurnal)
    {
        $jurnal->delete();
        return redirect()->route('jurnal.index')->with('success', 'Jurnal dihapus');
    }

    private function jurnalID(){
        
        $strings = "abcdefghijklmnopqrstuvwxyz";
        $numbers = mt_rand(11,99);
        $stridx1 = mt_rand(0,25);
        $stridx2 = mt_rand(0,25);
        $stridx3 = mt_rand(0,25);

        $string1 = $strings[$stridx1];
        $string2 = $strings[$stridx2];
        $string3 = $strings[$stridx3];

        $randomChar = $string1.$string2.$string3.$numbers;
        return strtoupper($randomChar);
    }
}

app/Http/Controllers/PresensiController.php
<?php

namespace App\Http\Controllers;

use App\Models\presensi;
use App\Models\jurnal;
use Illuminate\Http\Request;

class PresensiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hadir = presensi::paginate(20);
        return view('presensi.index')->with(['hadir' => $hadir]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function create()
    // {
    //     //
    // }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        presensi::create($request->all());
        return redirect()->to('hadir/' . $request->jurnals_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\presensi  $presensi
     * @return \Illuminate\Http\Response
     */
    public function show(presensi $presensi)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\presensi  $presensi
     * @return \Illuminate\Http\Response
     */
    public function edit(presensi $presensi)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\presensi  $presensi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, presensi $presensi)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\presensi  $presensi
     * @return \Illuminate\Http\Response
     */
    public function destroy(presensi $presensi)
    {
        //
    }

    public function hadir($jurnalID){
        $jurnal = jurnal::where('id', $jurnalID)->first();
        $hadir = presensi::orderBy('namaSiswa')->where('jurnals_id', $jurnalID)->get();
        return view('presensi.hadir', ['siswas' => $hadir,'jurnal'=>$jurnal]);
    }
}

resources/views/jurnal/detail.blade.php
@extends('templates.tutor')
@section('konten-utama')
    <div class="row">
        <div class="col-lg-4 mx-auto">
            <section class="page-title"><h4>Detil Jurnal</h4></section>
            <section class="page-content">
                <div class="list-group">
                    {{-- jurnalID , tanggal , kelas , pelajaran ,topik, tutor , dokumen --}}
                    <li class="list-group-item py-1">
                        <small><strong>ID Jurnal</strong></small>
                        <span class="float-end mr-3">{{ $jurnal->jurnalID }}</span>
                    </li>
                    <li class="list-group-item py-1">
                        <small><strong>Tanggal pembelajaran</strong></small>
                        <span class="float-end mr-3">{{ $jurnal->tanggal }}</span>
                    </li>
                    <li class="list-group-item py-1">
                        <small><strong>Kelas</strong></small>
                        <span class="float-end mr-3">{{ $jurnal->kelas }}</span>
                    </li>
                    <li class="list-group-item py-1">
                        <small><strong>Mata Pelajaran</strong></small>
                        <span class="float-end mr-3">{{ $jurnal->pelajaran }}</span>
                    </li>
                    <li class="list-group-item py-1">
                        <small><strong>Topik Bahasan</strong></small>
                        <span class="float-end mr-3">{{ $jurnal->topik }}</span>
                    </li>
                    <li class="list-group-item py-1">
                        <small><strong>Tutor</strong></small>
                        <span class="float-end mr-3">{{ $jurnal->tutor }}</span>
                    </li>
                    @php
                        $dokumen = json_decode($jurnal->dokumen);
                    @endphp
                    @foreach ($dokumen as $dok)
                    
                        <li class="list-group-item py-1">
                            <small><strong>Materi</strong></small><br/>
                            <span class="float-end mr-3">{{ $dok->materi }}</span>
                        </li>

                        <li class="list-group-item py-1">
                            <small><strong>Tugas</strong></small><br/>  
                            <span class="float-end mr-3">{{ $dok->tugas }}</span>
                        </li>

                    @endforeach
                </div>
                <div class="text-center">
                    <a href="{{ route('jurnal.index') }}" class="btn btn-sm btn-primary">Kembali</a>
                </div>
            </section>
        </div>
    </div>
@endsection
@section('memodalan')
    
@endsection
@section('sesekripan')
    
@endsection

resources/views/jurnal/form.blade.php
@php
if($jurnal!==null){
    $dokumen = json_decode($jurnal->dokumen,false);
    foreach($dokumen as $dok){
        $materi = $dok->materi;
        $tugas = $dok->tugas;
    }
}else{
        $materi = "Tidak Ada";
        $tugas = "Tidak Ada";
    }
@endphp

@extends('templates.tutor')

@section('konten-utama')
    <div class="row">
        <div class="col-md-6 mx-auto">
            <section class="page-title">
                <h4>Jurnal Hari Ini</h4>
            </section>
            <section class="page-content">
                @if ($jurnal !== null)
                    <form action="{{ route('jurnal.update',$jurnal->id) }}" method="post">  
                    @method('PATCH')
                @else
                    <form action="{{ route('jurnal.store') }}" method="post">                    
                @endif
                @csrf
                <input type="hidden" name="id" value="{{ $jurnal==null ? "" : $jurnal->id }}">
                <div class="mb-1 row">
                    <label for="jurnalID" class="col-md-4 text-right">Kode Jurnal</label>
                    <div class="col-md-8">
                        <input type="text" id="idJurnal" class="form-control" value="{{ $jurnal==null ? $jurnalID : substr($jurnalID,3,5) }}" readonly>
                        <input type="hidden" name="jurnalID" id="jurnalID" value="{{ $jurnal==null ? date('y').'-'.$jurnalID.'-'.sprintf('%03d',date('z')) : $jurnal->jurnalID }}">                        
                    </div>
                </div>
                <div class="mb-1 row">
                    <label for="tanggal" class="col-md-4 text-right">Tanggal</label>
                    <div class="col-md-8">
                        <input type="date" name="tanggal" id="tanggal" class="form-control" value="{{ $jurnal==null ? date('Y-m-d') : $jurnal->tanggal }}">
                    </div>
                </div>
                <div class="mb-1 row">
                    <label for="kelas" class="col-md-4 text-right">Kelas</label>
                    <div class="col-md-8">
                        <select name="kelas" id="kelas" class="form-control">
                            @php
                                $kelas =[
                                    '7'=>'Paket B - Kelas 7',
                                    '8'=>'Paket B - Kelas 8',
                                    '9'=>'Paket B - Kelas 9',
                                    '10'=>'Paket C - Kelas 10',
                                    '11'=>'Paket C - Kelas 11',
                                    '12'=>'Paket C - Kelas 12'
                                ];
                                
                            @endphp
                            @if ($jurnal !== null)
                                <option value="{{ $jurnal->kelas }}">{{ $kelas[$jurnal->kelas] }}</option>
                            @endif
                            @foreach ($kelas as $val=>$lbl)
                                <option value="{{ $val }}">{{ $lbl }}</option>
                            @endforeach
                            
                        </select>
                    </div>
                </div>
                <div class="mb-1 row">
                    <label for="pelajaran" class="col-md-4 text-right">Mata Pelajaran</label>
                    <div class="col-md-8">
                        <input type="text" name="pelajaran" id="pelajaran" class="form-control" value="{{ $jurnal == null ? "" : $jurnal->pelajaran }}">
                    </div>
                </div>
                <div class="mb-1 row">
                    <label for="topik" class="col-md-4 text-right">Topik Bahasan</label>
                    <div class="col-md-8">
                        <input type="text" name="topik" id="topik" class="form-control" value="{{ $jurnal == null ? "" : $jurnal->topik }}">
                    </div>
                </div>
                <div class="mb-1 row">
                    <label for="tutor" class="col-md-4 text-right">Nama Tutor</label>
                    <div class="col-md-8">
                        <input type="text" name="tutor" id="tutor" class="form-control" value="{{ $jurnal == null ? "" : $jurnal->tutor }}">
                    </div>
                </div>
                <div class="mb-1 row">
                    <label for="materi" class="col-md-4 text-right">Link Materi Pembelajaran</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" id="materi" value="{{ $materi }}">
                    </div>
                </div>
                <div class="mb-1 row">
                    <label for="tugas" class="col-md-4 text-right">Link Pengumpulan Tugas</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" id="tugas" value="{{ $tugas }}">
                    </div>
                </div>
                <input type="hidden" name="dokumen" id="dokumen">
                <div class="mb-1 container">
                    <div class="row">
                        <div class="col-4 mx-auto">
                            <div class="form-check justify-content-center">
                                <input class="form-check-input" type="checkbox" id="cekForm">
                                <label class="form-check-label" for="cekForm">
                                  Periksa Data
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4 mx-auto text-center">
                            <input type="submit" value="Catat Jurnal" id="submitJurnal" class="btn btn-dark btn-sm" style="visibility: hidden;">
                        </div>
                    </div>
                </div>
                
                </form>
            </section>
        </div>
    </div>
@endsection
@section('memodalan')
    
@endsection
@section('sesekripan')
    <script>
        $("#cekForm").click( function(){
            if( $(this).is(':checked')){
                $("#submitJurnal").css('visibility','visible');
                setDokumen();
            }else{
                $("#submitJurnal").css('visibility','hidden');
            }
        })

        function setDokumen(){
            let dokumen={'dokumen':{'materi':$("#materi").val() , 'tugas':$("#tugas").val()}}
            $("#dokumen").val(JSON.stringify(dokumen));
        }
    </script>
@endsection

resources/views/jurnal/index.blade.php
@php
    function formatTanggal($tanggal){
        list($t,$b,$h) = explode("-",$tanggal);
        return "$h-$b-$t";
    }
@endphp
@extends('templates.tutor')
@section('konten-utama')
    <div class="row">
        <div class="col">
            <section class="page-title"><h4>Jurnal Hari Ini</h4></section>
            <section class="page-nav">
                <a href="{{ route('jurnal.create') }}" class="btn btn-primary btn-sm">
                    <i class="bi bi-plus-circle"></i> Jurnal
                </a>
            </section>
            <section class="page-content">
                <table class="table table-sm table-bordered">
                    <thead>
                        <tr class="text-center bg-dark text-light">
                            <th>Tanggal</th>
                            <th>Tutor</th>
                            <th>Kelas</th>
                            <th>Pelajaran</th>
                            <th>Topik</th>
                            <th><i class="bi bi-menu-up"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($jurnals as $jurnal)
                            <tr>
                                <td>{{ formatTanggal($jurnal->tanggal) }}</td>
                                <td>{{ $jurnal->tutor }}</td>
                                <td class="text-center">{{ $jurnal->kelas }}</td>
                                <td>{{ $jurnal->pelajaran }}</td>
                                <td>{{ $jurnal->topik }}</td>
                                <td class="text-center">
                                    <form class="control" action="{{ route('jurnal.destroy',$jurnal->id) }}" method="post">
                                        <a href="{{ route('jurnal.show',$jurnal->id) }}" class="btn btn-sm btn-success">
                                            <i class="bi bi-list-ol"></i>
                                        </a>
                                        <a href="{{ route('jurnal.edit',$jurnal->id) }}" class="btn btn-sm btn-warning">
                                            <i class="bi bi-pencil-square"></i>
                                        </a>
                                        <a href="{{ url('hadir/'.$jurnal->id) }}" class="btn btn-info btn-sm">
                                            <i class="bi bi-check2-circle"></i>
                                        </a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-danger btn-sm"><i class="bi bi-x-octagon"></i></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </section>
        </div>
    </div>
@endsection
@section('memodalan')
    
@endsection
@section('sesekripan')
    
@endsection

resources/views/komponen/header.blade.php
<div class="row" id="page-header">
    <div class="col-lg-6">

        <h1 class="display-6">
            <p class="my-1">Jurnal Kegiatan Pembelajaran</p>
            <p class="lead">Sanggar kegiatan Belajar Kabupaten Banjarnegara</p>
        </h1>

    </div>
</div>

resources/views/komponen/js.blade.php
<script>
    const appurl = "{{ url('/') }}";
    const apiurl = "{{ url('/api') }}";
</script>

resources/views/presensi/hadir.blade.php
@extends('templates.tutor')
@section('konten-utama')
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <section class="page-title"><h4>Prensensi</h4></section>
            <section class="page-content">
                <form action="{{ route('presensi.store') }}" method="post">
                    @csrf
                    <div class="form-group row mb-2">
                        <label for="jurnals_id" class="col-md-4">Kode Jurnal</label>
                        <div class="col-md-8">
                            <input type="hidden" id="jurnals_id" name="jurnals_id" value="{{ $jurnal->id }}">
                            <input type="text" id="jurnalID" class="form-control" readonly value="{{ $jurnal->jurnalID }}">
                        </div>
                    </div>
                    <div class="form-group row mb-2">
                        <label for="namaSiswa" class="col-md-4">Nama Siswa</label>
                        <div class="col-md-8">
                            <input type="text" name="namaSiswa" id="namaSiswa" class="form-control">
                        </div>
                    </div>
                    <div class="form-group py-2 justify-content-center">
                        <button type="submit" class="btn btn-primary">Hadir !</button>
                    </div>
                </form>
            </section>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="table-responsive py-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th width="100">No.</th>
                            <th>Siswa</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $nomor=1;
                        @endphp
                        @foreach ($siswas as $siswa)
                            <tr>
                                <td>{{ $nomor++ }}</td>
                                <td>{{ $siswa->namaSiswa }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('memodalan')
    
@endsection
@section('sesekripan')
    
@endsection

resources/views/presensi/index.blade.php
@extends('templates.tutor')
@section('konten-utama')    
    <div class="row">
        <div class="col">
            <section class="page-title"><h4>Kehadiran Warga Belajar</h4></section>
            <section class="page-content">

                <div class="table-responsive">
                    <table class="table table-sm table-striped">
                        <thead>
                            <tr>
                                <th>ID Jurnal</th>
                                <th>Tanggal</th>
                                <th>Pelajaran</th>
                                <th>Topik</th>
                                <th>Nama Siswa</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>

            </section>
        </div>
    </div>
@endsection
@section('memodalan')
    
@endsection
@section('sesekripan')
    
@endsection

resources/views/templates/tutor.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Jurnal PBM Eskabara</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    @include('komponen.js')
    <link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/128/1483/1483298.png" type="image/x-icon">
    <style>
      input.form-control{background-color: #e0e0e0;}
      form{ background-color: #c0d1dd; padding: 15px;}
      form.control {padding:0px;}
      #page-header{ background-color: black; color: silver;}
      section.page-title{padding-top: 15px; text-align: center;}
    </style>
  </head>
  <body>
    <div class="container-fluid">
      @include('komponen.header')
      <div class="row">
        <div class="col">
          @if ($message = Session::get('success'))
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ $message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          @endif
        </div>
      </div>
      @yield('konten-utama')
    </div>
    @yield('memodalan')
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    @yield('sesekripan')
  </body>
</html>